name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  GKE_CLUSTER: iris-cluster
  GKE_ZONE: us-central1
  REPOSITORY: iris-repo
  IMAGE: iris-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: iris-cluster
        location: us-central1

    - name: Build and Push Docker Image
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t iris-api ./app
        docker tag iris-api us-central1-docker.pkg.dev/rare-keep-460211-q6/iris-repo/iris-api:latest
        docker push us-central1-docker.pkg.dev/rare-keep-460211-q6/iris-repo/iris-api:latest

    - name: Deploy to GKE
      run: |-
        kubectl apply -f k8s/